<?php

/**
 * @file
 * This is a Feeds plugin that will fetch file from an URL.
 */

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_url_fetcher_feeds_plugins() {
  $info = array();
  $info['FeedsURLFetcher'] = array(
    'name' => 'URL Fetcher',
    'description' => 'Download content from a URL',
    'help' => 'Fetches files from URL by protocols supported by PHP',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'FeedsURLFetcher',
      'file' => 'FeedsURLFetcher.inc',
      'path' => backdrop_get_path('module', 'feeds_url_fetcher'),
    ),
  );
  return $info;
}

/**
 * Implementation of hook_autoload_info().
 */
function feeds_url_fetcher_autoload_info() {
  return array(
    'FeedsURLFetcher' => 'FeedsURLFetcher.inc',
    'FeedsURLFetcherResult' => 'FeedsURLFetcher.inc',
  );
}